### ISSUE TITLE
Use sans-serif font

### ISSUE THREAD

**Issue by beardhatcode** [unipept/unipept-visualizations#25]
Add option to add style to the main svg or make the SVG tag set `font-family: sans-serif`

https://github.ugent.be/unipept/unipept/pull/623#issuecomment-77880

_[Original issue](https://github.ugent.be/unipept/unipept-visualizations/issues/25) by @beardhatcode on Tue Jun 12 2018 at 17:20._
_Closed by @bmesuere on Wed Jun 13 2018 at 14:34._

**Comment by bmesuere** [comment]
fixed in 161f1378f85bec02ab8fe500c07f2882f5c53d1b

_[Original comment](https://github.ugent.be/unipept/unipept-visualizations/issues/25#issuecomment-77931) by @bmesuere on Wed Jun 13 2018 at 14:34._
