### ISSUE TITLE
Port sunburst visualisation to typescript

### ISSUE THREAD

**Issue by MaybeJustJames** [unipept/unipept-visualizations#30]
- [x]  Remove jQuery dependency
- [x]  Display test data in a d3.js v5 sunburst
- [x]  Port colouring
- [x]  Port breadcrumbs
- [x]  Port tooltips
- [x] Port node labels
- [x]  Clean up
- [x]  Add remaining documentation
- [x]  Add remaining tests
- [x] Add examples

**Comment by pverscha** [comment]
This issue has been resolved in #36
