### ISSUE TITLE
Integrate the heatmap visualisation

### ISSUE THREAD

**Issue by MaybeJustJames** [unipept/unipept-visualizations#32]
Heatmap code @ [https://github.com/unipept/unipept-heatmap](https://github.com/unipept/unipept-heatmap).

The following subtasks need to be completed:
- [x] Merge with unrelated histories
- [x] Integrate heatmap code into the source structure and use tooltips from unitpept-visualisations
- [x] Clean up the code if necessary
- [x] Add and missing documentation
- [x] Add any missing tests

**Comment by pverscha** [comment]
The heatmap has been integrated into the release of version 2.0 of the package.
