### ISSUE TITLE
Rename `colorProvider` setting to `nodeFillColor`

### ISSUE THREAD

**Issue by pverscha** [unipept/unipept-visualizations#67]
There are currently two different option settings for determining the color of a node: `nodeFillColor` and `colorProvider`. The `colorProvider` should be renamed to `nodeFillColor` and `nodeFillColor` should be removed in order to avoid confusing our users.

Note that we should also update the documentation and Observable notebook accordingly.

**Comment by bmesuere** [comment]
Should we add an alias and mark the old name as deprecated as a first step? Because otherwise this will break for existing users.

**Comment by pverscha** [comment]
Good point, I'll update it as you suggested :)

**Comment by pverscha** [comment]
After some more investigating, I found out that all settings related to color behave identically to how they behaved in version 1 of the visualizations, except for one: `nodeFillColor`.

Setting `nodeFillColor` to `(d) => "#00FF00"` results to this in v1.0 of the treeview:
![image](https://user-images.githubusercontent.com/9608686/115843676-5c098000-a41f-11eb-9f2f-32c774e07962.png)

And has no effect in v2.0:
![image](https://user-images.githubusercontent.com/9608686/115843718-6c215f80-a41f-11eb-8d91-a4f1238afba3.png)

This is due to the fact that no fill is set for the nodes in v2.0, which we should fix. I propose that we do not rename the option and that I fix the `nodeFillColor` setting. All behaviour will then be identical to v1.0

**Comment by pverscha** [comment]
Fixed in #68.
